language: php

env:
  global:
    - CI=true
  matrix:
    - TEST_DOC=false
    - TEST_DOC=true

php:
  - '5.6'
  - '7.0'
  - '7.1.3'
  - hhvm
  - nightly
  
scripts:
  - composer install
  - vendor\bin\phpunit